# Generated by Django 4.2.4 on 2023-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(choices=[(0, 'Beginner'), (1, 'SmallScale'), (2, 'LargeScale')], max_length=20)),
            ],
        ),
    ]
