# Generated by Django 4.2.4 on 2023-09-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('SmallScale', 'SmallScale'), ('LargeScale', 'LargeScale')], max_length=20),
        ),
    ]
