# Generated by Django 4.2.6 on 2024-02-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={},
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='tasks',
        ),
    ]
