# Generated by Django 4.2.6 on 2024-01-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='images',
            field=models.ImageField(upload_to='dashboard/inventory/Productimages'),
        ),
    ]
