# Generated by Django 4.2.6 on 2024-02-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farmerinventory',
            table='inventory',
        ),
    ]
