# Generated by Django 4.2.6 on 2024-02-18 15:13

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_farmerinventory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=50)),
                ('GalleryImage', models.ImageField(upload_to=inventory.models.user_directory)),
            ],
            options={
                'db_table': 'InventoryGallery',
            },
        ),
        migrations.RenameField(
            model_name='farmerinventory',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='farmerinventory',
            name='product_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='farmerinventory',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='inventory.inventorygallery'),
        ),
    ]
