# Generated by Django 4.2.6 on 2024-02-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorygallery_rename_images_farmerinventory_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventorygallery',
            table=None,
        ),
    ]
