# Generated by Django 4.2.6 on 2024-02-11 11:04

from django.db import migrations, models
import manage_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0002_farmer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=manage_account.models.user_directory),
        ),
        migrations.AlterModelTable(
            name='farmer',
            table='farmer',
        ),
    ]
